name: Deploy to EC2

on:
  push:
    branches: [ main ]  # Se ejecuta cuando se hace push a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Tu región
    
    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name tu-app-name \
          --deployment-config-name CodeDeployDefault.EC2OneAtATime \
          --deployment-group-name tu-deployment-group \
          --s3-location bucket=tu-bucket,key=app.zip,bundleType=zip
